# Generated by Django 3.1.7 on 2021-05-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210511_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherlocation',
            name='color',
        ),
    ]
