# Generated by Django 3.1.7 on 2021-05-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_weatherlocation_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlocation',
            name='city',
            field=models.CharField(default='null', max_length=20),
            preserve_default=False,
        ),
    ]
