# Generated by Django 3.1.7 on 2021-06-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20210615_1755'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='town',
            unique_together=set(),
        ),
    ]
