# Generated by Django 3.1.7 on 2021-06-15 23:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20210615_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
